# -*- coding: utf-8 -*-
"""02.Calculate moisture in the air(solution)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M-x8tEiFkrdK1Zv7u_imoaN3j2pGNeTA

# Calculate moisture in the air

* 이 자료는 Metpy를 이용하여 대기 중의 수증기량을 계산해 보는 교수학습자료이다.

* python3 환경에서 돌아가도록 작성하였다. 

* <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">크리에이티브 커먼즈 저작자표시-비영리-동일조건변경허락 4.0 국제 라이선스</a>에 따라 이용할 수 있다.

* 이 파일은 읽기 전용으로 공유되어 있기 때문에 [파일] - [드라이브에 사본 저장]을 하여 본인의 소유로 만든 후에 코드를 실행할 수 있다.

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="크리에이티브 커먼즈 라이선스" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>

# Required packages : Numpy, Pandas, Matplotlib, Metpy 

* 코랩을 사용하는 경우에 Numpy, Pandas, Matplotlib은 설치되어 있으므로 그냥 사용하면 된다.

* Anaconda를 이용하는 경우에도 Numpy, Pandas, Matplotlib는 기본적으로 설치가 되어 있을 것이다. 

* 만약 최신 버전으로 업데이트 하고 싶다면 다음의 Anaconda prompt에서 다음의 명령어로 업데이트 할 수 있다. 

> conda update numpy pandas matplotlib

* [Metpy] Metpy는 보통 따로 설치를 해 주어야 한다. 

> !pip install Metpy

* 구글 코랩에서도 Metpy를 사용하기 위해서는 다음과 같이 쉘 명령어로 설치해 줘야 사용할 수 있다. 

> !pip install Metpy

# About Metpy

(https://unidata.github.io/MetPy/latest/index.html) 는 날씨 데이터를 처리하기 위해 만들어진 모듈이다. 최근 꾸준히 개발되고 있으며, 습도 계산, 단열선도를 작성 등을 해볼 수 있다.
"""

#metpy를 설치해 보자.
!pip install metpy

"""제대로 설치되었는지 확인하기 위해 Metpy 중에서 metpy.calc 함수를 mpcalc 로 지정하여 불러 보자."""

import metpy.calc as mpcalc

"""에러가 발생하지 않았다면 제대로 Metpy를 사용할 수 있는 것이다.

# AWS 자료 준비

[기상자료 개방포털](https://data.kma.go.kr/cmmn/main.do) 에서는 지상자료를 공개하고 있다. 그 중에서 [데이터] - [기상 관측] - [지상] - [종관 기상 관측(ASOS)] - [데이터셋]에서 원하는 곳의 AWS 자료를 받을 수 있다. 

기온과 습도 자료를 AWS 자료로 부터 읽어서 작업을 해보자.

현재 이 구글 코랩의 작업공간에 데이터를 저장할 폴더를 "AWS_data" 라는 이름으로 생성해보자. 폴더 생성은 리눅스 shell 명령어로 가능한데, "!"를 붙이면 shell 명령어를 실행할 수 있다. 

나의 구글 드라이브에 관악산에서 관측한 AWS를 저장해 둔 csv 파일을 공유하고자 한다. 자료는 2018년 1월 동안 관측하여 분단위로 저장한 자료이다. wget를 이용하여 여러분의 [작업 영역]에 저장해 두자.
"""

#내 작업 공간에 쉘명령어를 사용하여 폴더를 만들 수 있다. 
#!를 앞에 붙여주면 shell 명령어를 실행한다. 
!mkdir AWS_data
print ("AWS_data is created...")

#wget을 이용하여 데이터 다운로드
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1NLHwhmqnikHC77DdkelYBPnpwkJv8_rb' -O AWS_data/SURFACE_ASOS_116_MI_2019-08_2019-08_2019.csv

"""# DataFrame으로 저장

AWS 자료를 Pandas의 DataFrame으로 저장하자.
"""

#package 불러오기
import pandas as pd

#데이터가 저장되어 있는 폴더명 설정
base_dr = 'AWS_data/'
filename = 'SURFACE_ASOS_116_MI_2019-08_2019-08_2019.csv'

df = pd.read_csv('{0}{1}'.format(base_dr, filename),
                 thousands = ',',
                 encoding= 'euc-kr')
df

"""# 자료의 시간 재설정 및 인덱스 지정

우리가 날짜 시간으로 생각한 컬럼은 그저 문자열(str)임을 확인할 수 있다. 그래프를 그리기 위해서는 문자열을 to_datetime 메소드를 이용하여 날짜와 시간으로 바꿔줄 필요가 있다.

데이터를 보니 1분 간격으로 저장한 것 같고, 시작이 2018-01-01 00:01, 끝이 2018-02-01 00:00 인 것으로 보아 ['일시'] 컬럼의 시간 직전 1분간의 자료가 저장되어 있음을 알 수 있다.

datetime을 정확하게 이용하기 위하여 1분씩 빼서 저장하는 것이 더 나을것 같다. 1분씩 뺀 후에 index로 지정해 주자.
"""

df['dt_YmdHM'] = pd.to_datetime(df['일시'])

from datetime import timedelta
df['dt_YmdHM-1min'] = df['dt_YmdHM'] - timedelta(minutes = 1)
df.index = df['dt_YmdHM-1min']
df

"""# 인덱싱 방법

특정 시각("2019-08-15 01:00")의 기온(°C)과 습도(%) 값만 읽어보자.
"""

t_A = df.loc["2019-08-15 01:00", "기온(°C)"]
rh_A = df.loc["2019-08-15 01:00", "습도(%)"]

print("공기덩이 A의 기온(°C): {}".format(t_A))
print("공기덩이 A의 습도(%): {}".format(rh_A))

"""type 함수를 이용하여 특정 시각의 기온(°C)과 습도(%) 값의 데이터형을 조사해 보자. """

print("type(t_A): {}".format(type(t_A)))
print("type(rh_A): {}".format(type(rh_A)))

"""# Using metpy.units

[metpy.units](https://unidata.github.io/MetPy/latest/tutorials/unit_tutorial.html) 함수를 이용하면 dataframe에 단위를 입력할 수 있다. 이 단위는 [pint](https://pint.readthedocs.io/en/stable/developers_reference.html#module-pint)를 사용하는 것이다. 

"""

from metpy.units import units as u

v_distance = 8*u.m
v_time = 3*u.s

average_velocity = v_distance / v_time
average_velocity

"""type 함수로 어떤 데이터가 들어 있는지 확인해 보자. Quantity 가 들어 있음을 알 수 있다."""

print("type(v_distance):{}".format(type(v_distance )))
print("type(average_velocity):{}".format(type(average_velocity)))

"""string format을 이용하여 소수점 자리수를 설정할 수도 있다."""

"{0:0.03f}".format(average_velocity)

"""# Using metpy.calc

수증기의 열역학을 계산할 수 있는 [metpy.calc](https://unidata.github.io/MetPy/latest/api/generated/metpy.calc.html?highlight=calc#module-metpy.calc) 함수의 정보를 확인해 보자. 

metpy.calc 함수들은 dataframe 컬럼으로 계산을 하지 못하고, 단위를 포함한 pint.Quantity 객체를 변수로 입력해서 계산을 하도록 설계가 되어있다.

## 이슬점 온도 (dewpoint temperature)

먼저 이슬점 온도를 구해보자. dewpoint_from_relative_humidity 함수는 기온과 상대습도로 이슬점 온도를 구해준다. df의 특정 인덱스와 컬럼을 지정하여 특정한 날의 기온과 상대습도를 불러 보자.
"""

t_A = df.loc["2019-08-15 01:00", "기온(°C)"]
rh_A = df.loc["2019-08-15 01:00", "습도(%)"]

print("t_A: {}".format(t_A))
print("rh_A: {}".format(rh_A))

print("type(t_A): {}".format(type(t_A)))
print("type(rh_A): {}".format(type(rh_A)))

"""float type으로 저장되어 있는 데이터를 metpy.unit 함수를 이용하여 pint.Quantity로 변환해 주자."""

from metpy.units import units as u

t_A = df.loc["2019-08-15 01:00", "기온(°C)"] * u.degC
rh_A = df.loc["2019-08-15 01:00", "습도(%)"] * u.percent

print("t_A: {}".format(t_A))
print("rh_A: {}".format(rh_A))

print("type(t_A): {}".format(type(t_A)))
print("type(rh_A): {}".format(type(rh_A)))

"""이제 dewpoint_from_relative_humidity 함수를 이용하여 이슬점 온도를 구할 수 있다."""

import metpy.calc as mpcalc
from metpy.units import units as u

t_A = df.loc["2019-08-15 01:00", "기온(°C)"] * u.degC
rh_A = df.loc["2019-08-15 01:00", "습도(%)"] * u.percent

dewpoint_A = mpcalc.dewpoint_from_relative_humidity(t_A, rh_A)

print("공기덩이 A의 기온(°C): {}".format(t_A))
print("공기덩이 A의 습도(%): {}".format(rh_A))
print("공기덩이 A의 이슬점 온도(°C): {}".format(dewpoint_A))
print("type(dewpoint_A): {}".format(type(dewpoint_A)))

print("type(dewpoint_A): {}".format(type(dewpoint_A)))

"""다음과 같이 출력해 볼 수도 있을 것 같다."""

print('The magnitude of dewpoint temperature is {0.magnitude} with units {0.units}'.format(dewpoint_A))

"""## 혼합비(mixing ratio)

혼합비(Mixing Ratio)는 건조 공기 $1 \rm{~kg}$에 들어 있는 수증기의 양을 $ \rm{~g}$으로 나타낸 것이다.
        
$$ {\displaystyle	{
    \text { 혼합비 }=\frac{\text { 수증기 질량 }(\mathrm{g})}{\text { 건조 공기 질량 }(\mathrm{kg})} 
} 		} 	$$		

$$ {\displaystyle	{
    M.R.=\frac{m_{w}}{m_{d}}=\frac{\rho_{w}}{\rho_{d}} = 622 \frac{e}{p-e}(\mathrm{g} / \mathrm{kg})
} 		} 	$$		

이상기체 상태방정식을 이용해 구해볼 수 있다.
$$ {\displaystyle	{
    \begin{aligned}
        p&=\rho R T, \quad \rho=\frac{p}{R T} \\
        e&=\rho_w R_w T, \quad \rho_w=\frac{e}{R_w T} \\
        M.R.&=\frac{\rho_w}{\rho_d} = \frac{\frac{e}{R_w T}}{\frac{\left(p-e\right)}{R_d T}} = \frac{M_w}{M_d}\frac{e}{p-e}
    \end{aligned}
}	} $$

혼합비를 구하려면 기압값을 알아야 한다. 현지기압값이 Nan으로 되어 있는데, 아마 측정을 하지 않은 것으로 생각된다. 이 값을 1000으로 입력하자.
"""

p_A = 1000 *u.hPa

"""matpy.calc로 혼합비를 구해보자. """

print(p_A, t_A, rh_A)
mixing_ratio_A = mpcalc.mixing_ratio_from_relative_humidity(p_A, t_A, rh_A)
print("공기덩이 A의 혼합비: {:02f}".format(mixing_ratio_A))
mixing_ratio_A.magnitude

"""## 비습(specific humidity)

비습(Specific Humidity)은 수증기와 혼합되어 있는  $1 \rm{~kg}$에 들어 있는 수증기의 양을 $ \rm{~g}$으로 나타낸 것이다. 

$$ {\displaystyle	{
    \begin{aligned}
        &\text { 비습 }=\frac{\text { 수증기 질량 }(\mathrm{g})}{\text { 습윤 공기 질량 }(\mathrm{kg})} \\
        &S.H. = \frac{m_{w}}{m_{d}+m_{w}}=\frac{\rho_{w}}{\rho_{d}+\rho_{w}} = 622 \frac{e}{p}(\mathrm{g} / \mathrm{kg}) 
    \end{aligned}
}	} 	$$	


matpy.calc로  비습을 구해보자.
"""

print(p_A, dewpoint_A)
specific_humidity_A = mpcalc.specific_humidity_from_dewpoint(p_A, dewpoint_A)
print("공기덩이 A의 비습: {:02f}".format(specific_humidity_A))

"""## 수증기압(vaper pressure)

위의 결과로 수증기압을 구해보자.
"""

print(p_A, mixing_ratio_A)
vapor_pressure_A = mpcalc.vapor_pressure(p_A, mixing_ratio_A)
print("공기덩이 A의 수증기압: {:02f}".format(vapor_pressure_A))

"""## 습구 온도(wet bulb temperature)

습구 온도는 다음과 같이 구해볼 수 있다.

"""

print(p_A, t_A, dewpoint_A)
wet_bulb_temperature_A = mpcalc.wet_bulb_temperature(p_A, t_A, dewpoint_A)
print("공기덩이 A의 습구 온도: {:02f}".format(wet_bulb_temperature_A))

"""## 절대 습도(absolute humidity)

혼합공기 $1 \rm{~m^3}$에 들어있는 수증기의 양을 $\rm{g}$으로 나타낸 것으로 다음과 같이 구할 수 있다. 
$$ {\displaystyle	{
    \text { 절대습도 }=\frac{\text { 수증기 질량 }(\mathrm{g})}{\text { 공기 부피 }\left(\mathrm{m}^{3}\right)} 
}	}$$
				
이상기체 상태방정식으로 밀도를 구하면 
$$ {\displaystyle	{
    e = {\rho} R T, \quad \rho = \frac{e}{R T}
}	} $$
와 같다. 수증기의 밀도($\rho_w$)는 
$$ {\displaystyle	{
    \rho_{v}=\frac{e}{R_v T}
} 	} $$
$$ {\displaystyle	{
    \begin{aligned}
    R = M {\bar {R}} &= 8.3144 \left(\rm J~mol^{-1}~K^{-1}\right)  \\
				&= 8.3144 \left(\rm Pa~m^3~mol^{-1}~K^{-1}\right)
				\end{aligned}
}	}	$$

특별기체상수(specific gas constant)는 보편기체상수(${\bar{R}}$)를 기체의 분자량$\left(M\right)$으로 나누어 구할 수있다. 
$$ {\displaystyle	{
    R = \frac{\bar{R}}{M}
}	}	$$
수증기의 기체상수는
$$ {\displaystyle	{
    {{R_v}}={\frac {R}{M_v}} = {\frac {8.3144}{18}} = 0.461 \left(\rm J~g^{-1}~K^{-1}\right)
}	}$$

$$ {\displaystyle	{
    A. H.= \rho_{v}=\frac{e}{R_v T} = 217 \frac{e}{T} \left(\mathrm{g}~\mathrm{m}^{-3}\right)
} 		} 	$$
단, 여기에서 $\mathrm{e}: \mathrm{hPa}$, $\mathrm{T}: \mathrm{K}$ 단위이다.

## (과제)

metpy.calc에 절대습도를 구하는 함수는 존재하지 않는다. 위의 식을 이용하여 다음과 같이 절대습도를 구하는 함수를 직접 만들어 보자.

* 함수 이름 : absolute_humidity_from_vapor_pressure
* 입력 변수1 : #vapor preuusure (pint.Quantity) – hectopascal
* 입력 변수2 : #temperature (pint.Quantity) – degree_Celsius
* 출력 : #absolute humidity (pint.Quantity) – gram/meter3

함수를 만든 후 공기덩이 A의 절대습도를 구해보자.
"""

# 이곳에 코딩을 완성하여 제출하시오.

def absolute_humidity_from_vapor_pressure(vapor_pressure, temprature) :
    ####################################
    #Calculate the absolute humidity.
    #Uses vapor pressure(hPa) and temperature(degC) to calculate absolute humidity
    #Parameters
    #vapor preuusure (pint.Quantity) – hectopascal
    #temperature (pint.Quantity) – degree_Celsius
    #
    #Returns : absolute humidity (pint.Quantity) – gram/meter3
    ah = (18/8.3144)*u.g *u.degK /(u.N*u.m) * (vapor_pressure.to(u.Pa).to(u.N/((u.m)*(u.m)))) / temprature.to(u.degK)
    return ah

absolute_humidity_from_vapor_pressure(vapor_pressure_A, t_A)

"""# dataframe과 metpy.calc

아래 셀은 dataframe 컬럼으로 계산을 시도해 본 것인데, metpy.calc 함수들은 dataframe 컬럼으로 계산을 하지 못하고, 단위를 포함한 pint.Quantity 객체를 변수로 입력해서 계산을 하도록 설계가 되어있다.
"""

df['dewpoint_A'] = mpcalc.dewpoint_from_relative_humidity(df["기온(°C)"].values* u.degC, 
                                                        df["습도(%)"].values* u.percent)

"""## for ~ loop 문을 이용한 처리 

그래서 어쩔수 없이 속도는 느리지만 한 행마다 자료를 읽어서 for ~ loop문으로 처리를 해 보자. dataframe의 한 행씩 for ~loop를 할때는 df.iterrows()를 사용할 수 있다. 

"""

import metpy.calc as mpcalc
from metpy.units import units as u
    
for idx, row in df.iterrows():
    print("idx: {}".format(idx))
    print("row: {}".format(row))
    print("row['기온(°C)']: {}".format(row['기온(°C)']))
    break

"""dataframe의 각행에서 값을 읽어 단위를 곱한 후에 metpy.calc 함수를 이용하여 원하는 물리량을 계산한 후, 해당 행에 저장할 수 있다. 

해당 행에 저장하는 방법은 다음과 같다. 

> df.at[idx, "T_d"] = 

아래는 이슬점 온도를 구하여 저장하는 코드이다. 1달 동안의 모든 자료를 한줄씩 계산해야 하므로 시간이 좀 걸릴 것이다.
"""

import metpy.calc as mpcalc
from metpy.units import units as u
    
for idx, row in df.iterrows():
    
    #for debug
    #print(idx, row)
    #print("df.loc[idx, '기온(°C)']*u.degC: {}".format(df.loc[idx, '기온(°C)']*u.degC))
    #print("df.loc[idx, '습도(%)']*u.percent: {}".format(df.loc[idx, '습도(%)']*u.percent))
    #print("type(df.loc[idx, '기온(°C)']*u.degC): {}".format(type(df.loc[idx, '기온(°C)']*u.degC)))
    #print("type(df.loc[idx, '습도(%)']*u.percent: {}".format(type(df.loc[idx, '습도(%)']*u.percent)))

    df.at[idx, "T_d"] = mpcalc.dewpoint_from_relative_humidity(df.loc[idx, '기온(°C)'] *u.degC, 
                                                            df.loc[idx, '습도(%)'] *u.percent).magnitude          
                                                                
    print("idx, df.loc[idx, 'T_d']: {}, {}".format(idx, df.loc[idx, 'T_d']))

df

"""## dataframe 체크해 보기

특정 시간의 특정 데이터가 비어 있으면 계산을 하지 못할 수 있기 때문에 각 컬럼에서 비어 있는 자료가 있는지 체크해 볼 필요가 있겠다. 

series로 반환하여 s.isnull() method를 사용하면 bool 값을 반환해 주는데, 갯수를 알고 싶으면 s.isnull()sum()으로 합을 구해보면 될 것이다. 
"""

print("df['기온(°C)'].isnull(): {}".format(df['기온(°C)'].isnull()))
print("df['기온(°C)'].isnull().sum(): {}".format(df['기온(°C)'].isnull().sum()))
print("df['습도(%)'].isnull().sum(): {}".format(df['습도(%)'].isnull().sum()))

"""'습도(%)' 컬럼에서 213개의 행에 자료가 없는 것이 확인되었다. 자료가 없는 것을 제외한 subset을 만들어 보자."""

df.dropna(axis=0,subset=['기온(°C)', '습도(%)'])['기온(°C)']
df.dropna(axis=0,subset=['기온(°C)', '습도(%)'])['습도(%)']
df.dropna(axis=0,subset=['기온(°C)', '습도(%)'])

print(len(df))
print(len(df.dropna(axis=0,subset=['기온(°C)', '습도(%)'])))

"""subset을 이용하여 다시 for ~ loop를 돌려보는 방법도 있다. """

import metpy.calc as mpcalc
from metpy.units import units as u
    
for idx, row in df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).iterrows():
    
    #for debug
    #print(idx, row)
    #print("df.loc[idx, '기온(°C)']*u.degC: {}".format(df.loc[idx, '기온(°C)']*u.degC))
    #print("df.loc[idx, '습도(%)']*u.percent: {}".format(df.loc[idx, '습도(%)']*u.percent))
    #print("type(df.loc[idx, '기온(°C)']*u.degC): {}".format(type(df.loc[idx, '기온(°C)']*u.degC)))
    #print("type(df.loc[idx, '습도(%)']*u.percent: {}".format(type(df.loc[idx, '습도(%)']*u.percent)))

    df.at[idx, "T_d"] = mpcalc.dewpoint_from_relative_humidity(df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, '기온(°C)'] *u.degC, 
                                                            df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, '습도(%)'] *u.percent).magnitude          
                                                                
    print("idx, df.loc[idx, 'T_d']: {}, {}".format(idx, df.loc[idx, 'T_d']))
    break 
    
df

"""## error handling

for ~ loop 문이 실행되는 동안에 error가 발생하면 loop가 중단된다. error가 발생하더라도 loop가 중단되지 않게 하려면 다음과 같이 하는 방법도 있다.
"""

import metpy.calc as mpcalc
from metpy.units import units as u

for idx, row in df.iterrows():
    try :
        #for debug
        #print(idx)
        
        #print("df.loc[idx, '기온(°C)']*u.degC: {}".format(df.loc[idx, '기온(°C)']*u.degC))
        #print("df.loc[idx, '습도(%)']*u.percent: {}".format(df.loc[idx, '습도(%)']*u.percent))
        #print("type(df.loc[idx, '기온(°C)']*u.degC): {}".format(type(df.loc[idx, '기온(°C)']*u.degC)))
        #print("type(df.loc[idx, '습도(%)']*u.percent: {}".format(type(df.loc[idx, '습도(%)']*u.percent)))
        #print(mpcalc.dewpoint_from_relative_humidity(df.loc[idx, '기온(°C)']*u.degC, df.loc[idx, '습도(%)']*u.percent))
        #print(type(mpcalc.dewpoint_from_relative_humidity(df.loc[idx, '기온(°C)']*u.degC, df.loc[idx, '습도(%)']*u.percent)))
                                                         
        df.at[idx, 'T_d'] = mpcalc.dewpoint_from_relative_humidity(df.loc[idx, '기온(°C)']*u.degC, 
                                                        df.loc[idx, '습도(%)']*u.percent).magnitude
        print("idx, df.loc[idx, 'T_d']: {}, {}".format(idx, df.loc[idx, 'T_d']))
        break                                                   
        
    except Exception as err: 
        print("{} error :{}".format(idx, err))
        break 

df

"""subset과 error handling 을 모두 적용한 것이다."""

import metpy.calc as mpcalc
from metpy.units import units as u

for idx, row in df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).iterrows():
    try :
        #for debug
        #print(idx)
        #print(idx, row)
        #print("df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, '기온(°C)']*u.degC: {}".format(df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, '기온(°C)']*u.degC))
        #print("df.loc[idx, '습도(%)']*u.percent: {}".format(df.loc[idx, '습도(%)']*u.percent))
        #print("type(df.loc[idx, '기온(°C)']*u.degC): {}".format(type(df.loc[idx, '기온(°C)']*u.degC)))
        #print("type(df.loc[idx, '습도(%)']*u.percent: {}".format(type(df.loc[idx, '습도(%)']*u.percent)))
        #print(df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, '기온(°C)'] *u.degC)
        
        df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).at[idx, "T_d"] =  \
                        mpcalc.dewpoint_from_relative_humidity(df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, '기온(°C)']*u.degC, \
                        df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, '습도(%)']*u.percent).magnitude
                                                                    
        print("idx, df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, 'T_d']: {}, {}".format(idx, df.dropna(axis=0,subset=['기온(°C)', '습도(%)']).loc[idx, 'T_d']))
        break 

    except Exception as err: 
        print("{} error :{}".format(idx, err))
        break 
        
df

"""## 기압값 입력 

AWS 자료에는 해면기압(hPa) 값이 NaN 이다. 할수 없이 기압을 1000 hPa로 정해서 dataframe에 입력해 보자. 
"""

df['현지기압(hPa)'] = 1000
df

"""## (과제)

위의 예제를 응용하여 다음의 물리량들을 계산하여 dataframe에 새로운 컬럼에 입력해 보자.

* 이슬점 온도 : 'T_d(°C)'
* 혼합비 : 'MR(unitless)'
* 비습 : 'SH(unitless)'
* 수증기압 : 'VP(hPa)'
* 습구온도 : 'T_wb(°C)' (현재는 에러로 산출 불가함.)
* 절대 습도 : 'AH(g/cm^3)'
"""

#(과제) 아래에 코딩을 완성하여 제출하시오.

import metpy.calc as mpcalc
from metpy.units import units as u
    
for idx, row in df.iterrows():
    try :
        #for debug
        #print(idx, row)
        
        #이슬점 온도
        df.at[idx, 'T_d(°C)'] = mpcalc.dewpoint_from_relative_humidity(df.loc[idx, '기온(°C)']*u.degC, 
                                            df.loc[idx, '습도(%)']*u.percent).magnitude
        #print("T_d(°C)")
        print("idx, df.loc[idx, 'T_d(°C)']: {}, {}".format(idx, df.loc[idx, 'T_d(°C)']))

        # 혼합비
        df.at[idx, 'MR(unitless)'] = mpcalc.mixing_ratio_from_relative_humidity(df.loc[idx, '현지기압(hPa)']*u.hPa, 
                                            df.loc[idx, '기온(°C)']*u.degC, 
                                            df.loc[idx, '습도(%)']*u.percent).magnitude
        #print("MR(unitless)")
        print("idx, df.loc[idx, 'MR(unitless)']: {}, {}".format(idx, df.loc[idx, 'MR(unitless)']))

        #비습 
        df.at[idx, 'SH(unitless)'] = mpcalc.specific_humidity_from_dewpoint(df.loc[idx, '현지기압(hPa)']*u.hPa, 
                                            df.loc[idx, 'T_d(°C)']*u.degC).magnitude
        #print("SH(unitless)")
        print("idx, df.loc[idx, 'SH(unitless)']: {}, {}".format(idx, df.loc[idx, 'SH(unitless)']))
        
        #수증기압 
        df.at[idx, 'VP(hPA)'] = mpcalc.vapor_pressure(df.loc[idx, '현지기압(hPa)']*u.hPa, 
                                            df.loc[idx, 'MR(unitless)']).magnitude
        #print("VP")
        print("idx, df.loc[idx, 'VP(hPA)']: {}, {}".format(idx, df.loc[idx, 'VP(hPA)']))

        #습구 온도 
        #for debug
        #print(type(df.loc[idx, '현지기압(hPa)']))
        #print(type(df.loc[idx, '기온(°C)']))
        #print(type(df.loc[idx, 'T_d(°C)']))
        #print(df.loc[idx, '현지기압(hPa)']*u.hPa)
        #print(df.loc[idx, '기온(°C)']*u.degC)
        #print(df.loc[idx, 'T_d(°C)']*u.degC)
        #print(type(df.loc[idx, '현지기압(hPa)']*u.hPa))
        #print(type(df.loc[idx, '기온(°C)']*u.degC))
        #print(type(df.loc[idx, 'T_d(°C)']*u.degC))
        #print(mpcalc.wet_bulb_temperature(df.loc[idx, '현지기압(hPa)']*u.hPa, 
        #                                  df.loc[idx, '기온(°C)']*u.degC, 
        #                                  df.loc[idx, 'T_d(°C)']*u.degC).magnitude)
        #df.at[idx, 'T_wb(°C)'] = mpcalc.wet_bulb_temperature(df.loc[idx, '현지기압(hPa)']*u.hPa, 
        #                                    df.loc[idx, '기온(°C)']*u.degC, 
        #                                    df.loc[idx, 'T_d(°C)']*u.degC).magnitude
        #print("T_wb(°C)")
        #print("idx, df.loc[idx, 'T_wb(°C)']: {}, {}".format(idx, df.loc[idx, 'T_wb(°C)']))        
        
        #절대 습도
        df.at[idx, 'AH(g/cm^3)'] = absolute_humidity_from_vapor_pressure(df.loc[idx, 'VP(hPA)']*u.hPa, 
                                            df.loc[idx, '기온(°C)']*u.degC).magnitude
        #print("AH")
        print("idx, df.loc[idx, 'AH(g/cm^3)']: {}, {}".format(idx, df.loc[idx, 'AH(g/cm^3)']))
        #break

    except Exception as err: 
        print("{} error :{}".format(idx, err))
        #break

df

"""이제 dataframe을 csv 파일로 저장해 보자."""

df

df.to_csv("{}_result.csv".format(filename[:-4]))
print("{}_result.csv is created...".format(filename[:-4]))